name = "CategoryEncoder"
uuid = "9b7f5c8e-2d4a-4e7d-b6e2-9f5b8c0c1234"
version = "0.1.0"
authors = ["Clébio Júnior <clebiomojunior@gmail.com>"]

[deps]
CatBoost = "e2e10f9a-a85d-4fa9-b6b2-639a32100a12"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
LightGBM = "7acf609c-83a4-11e9-1ffb-b912bcd3b04a"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"

[compat]
CatBoost = "0.3.5"
CategoricalArrays = "1.0.2"
DataFrames = "1.8.1"
DecisionTree = "0.12.4"
LightGBM = "2.1.0"
MLJ = "0.22.0"
MLJDecisionTreeInterface = "0.4.3"
MLJLinearModels = "0.10.1"
MLJModelInterface = "1.12.1"
julia = "1.9"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
JLD2 = "033835bb-8acc-5f60-bf32-7f2c1e4b7d8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CSV", "Plots", "StatsPlots", "JLD2"]
